### ISSUE TITLE
NDE/NIE incompatibility with ATE 

### ISSUE THREAD

**Issue by jbriggs7** [tlverse/tmle3mediate#5]
Hi, 

I was using tmle3mediate for a project and noted that the ATE estimated by adding the NIE and NDE together is a bit different than the estimate of the ATE you get without using tmle3mediate, using just tmle3. It would be nice if the tmle3mediate package returned the ATE w/confidence intervals as part of the object returned. Thanks!

**Comment by nhejazi** [comment]
thanks for using the package, great to see it was useful. would you mind providing some more specifics (or numerical examples) of how different the results are exactly? the effect decomposition ATE = NDE + NIE always holds (up to identification conditions) but the estimates themselves need not be compatible. specifically, the estimated NDE is based on a targeting procedure designed to efficiently estimate the NDE functional, but the bias-correction procedure that makes the TML estimate of the NDE asymptotically linear and efficient does not necessarily solve the ATE estimating equation, leading to some kind of incompatibility. the same is true for the NIE, so it would surprise me if we actually did see \hat{NDE} + \hat{NIE} = \hat{ATE}.

in practice, if were were to try to guarantee that \hat{NDE} + \hat{NIE} = \hat{ATE}, then we'd require a joint targeting procedure guaranteed to solve the three different EIF estimating equations simultaneously. this can be done with the `tmle3` framework, but it's very unlikely that this will be implemented. on the other hand, if the numerical difference is relatively large, there may be a bug and that could potentially be investigated
